### ISSUE TITLE
Debugging is GL 4.3 + only.

### ISSUE THREAD

**Issue by kosude** [kosude/orion#1]
Some sort of backwards-compatible debugging solution should be implemented for older versions of OpenGL.

**Comment by jabenuk** [comment]
Will look at querying GL extensions like [ARB_debug_output](https://www.khronos.org/registry/OpenGL/extensions/ARB/ARB_debug_output.txt) or [KHR_debug](https://www.khronos.org/registry/OpenGL/extensions/KHR/KHR_debug.txt) for older versions of OpenGL where the debug context is not part of the core API.

If an implementation doesn't even support these extensions, then convenient OpenGL debug output might just be out of the question.

**Comment by kosude** [comment]
Repository archived / **Issue closed**.
